# Generated by Django 5.0.4 on 2024-05-03 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_guestlist_alter_guest_message_guest_guest_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='main.guestlist'),
            preserve_default=False,
        ),
    ]
