# Generated by Django 5.0.4 on 2024-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_guest_first_name_remove_guest_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='guest',
            name='viewed_invitation',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
