# Generated by Django 5.0.4 on 2024-05-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_guest_address_remove_guest_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='number_of_guests',
            new_name='number_of_guests_attending',
        ),
        migrations.AddField(
            model_name='guest',
            name='number_of_guests_invited',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
