# Generated by Django 5.0.4 on 2024-05-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_guest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='number_of_guests_attending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='number_of_guests_invited',
            field=models.IntegerField(default=0),
        ),
    ]
