# Generated by Django 5.0.4 on 2024-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_guest_number_of_guests_attending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
