# Generated by Django 5.0.4 on 2024-05-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_guest_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='identification',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
