# Generated by Django 5.0.4 on 2024-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_guest_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='viewed_invitation',
        ),
    ]
