# Generated by Django 5.0.4 on 2024-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_guest_viewed_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
