# Generated by Django 5.0.4 on 2024-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_guest_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
